---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-5.11
- name: centos-6.6
- name: ubuntu-10.04
  run_list:
    - recipe[apt]
- name: ubuntu-12.04
  run_list:
    - recipe[apt]
- name: ubuntu-14.04
  run_list:
    - recipe[apt]

suites:
- name: default
  run_list:
    - recipe[erlang]

- name: gui_tools
  run_list:
    - recipe[erlang]
  attributes:
    erlang:
      gui_tools: true
  excludes:
    - centos-5.11
    - centos-6.6

- name: esl
  run_list:
    - recipe[erlang::esl]
  excludes:
    - centos-5.11

- name: source
  run_list:
    - recipe[erlang::source]
