AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - Rakefile
    - metadata.rb

Style/PercentLiteralDelimiters:
  Exclude:
    - metadata.rb
